import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for Peter Pan's Techland
 * Using autogenerated sidebars from folder structure
 */
const sidebars: SidebarsConfig = {
  // Main sidebar - autogenerated from docs folder structure
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
